[theme]
base="light"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[server]
runOnSave = true
enableCORS = false
enableXsrfProtection = false
headless = true
maxUploadSize = 30
enableWebsocketCompression = true